export const usersMock = [
  { label: "Alice", value: "1" },
  { label: "Bob", value: "2" },
  { label: "Charlie", value: "3" },
  { label: "David", value: "4" },
  { label: "Eve", value: "5" },
  { label: "Frank", value: "6" },
  { label: "Grace", value: "7" },
  { label: "Hank", value: "8" },
  { label: "Ivy", value: "9" },
  { label: "Jack", value: "10" },
  { label: "Kate", value: "11" },
  { label: "Liam", value: "12" },
  { label: "Mia", value: "13" },
  { label: "Noah", value: "14" },
  { label: "Olivia", value: "15" },
  { label: "Parker", value: "16" },
  { label: "Quinn", value: "17" },
  { label: "Ryan", value: "18" },
  { label: "Sophia", value: "19" },
  { label: "Thomas", value: "20" },
  { label: "Ursula", value: "21" },
  { label: "Violet", value: "22" },
  { label: "William", value: "23" },
  { label: "Xavier", value: "24" },
  { label: "Yasmine", value: "25" },
  { label: "Zach", value: "26" },
];
